### ISSUE TITLE
Mix deps.get hanging

### ISSUE THREAD

**Issue by lukashambsch** [riverrun/bcrypt_elixir#26] opened 2019-11-02 14:40 UTC
I'm trying to upgrade from elixir 1.8.1 to 1.9.2. After upgrading, I get this error when running `mix test`:

```
could not compile dependency :bcrypt_elixir, "mix compile" failed. You can recompile this dependency with "mix deps.compile bcrypt_elixir", update it with "mix deps.update bcrypt_elixir" or clean it with "mix deps.clean bcrypt_elixir"
==> any_gym_planner
** (Mix) Could not compile with "make" (exit status: 69).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

So I checked the versions of `bcrypt_elixir` and noticed that there is now a version 2. So I tried upgrading to version 2 and when I run `mix deps.get` it just hangs after outputting `Resolving Hex dependencies...`. Any ideas on what would cause this?

**Comment by lukashambsch** [comment] 2019-11-02 15:26
The first error seems to be resolved by accepting the xcode agreement (not sure what effect the elixir upgrade had on this). But it's still hanging when I try to upgrade `bcrypt_elixir` to `2.0`.

**Comment by riverrun** [comment] 2019-11-04 00:33
I am not sure if this will make a difference, but please make sure that `comeonin` is not in the list of dependencies in the mix.exs file.

I will look into this issue further and get back to as soon as I can.

**Comment by lukashambsch** [comment] 2019-11-04 23:42
It is not in the mix.exs file. But I do see it in the mix.lock file.

**Comment by riverrun** [comment] 2019-11-05 01:08
Ok. I will try to find out more about this problem and get back to you soon.

**Comment by riverrun** [comment] 2020-01-08 06:59
In [this issue](https://github.com/elixir-lang/elixir/issues/9374), they suggest upgrading hex to solve a similar problem. Could you try that and let me know if it works?

**Comment by lukashambsch** [comment] 2020-01-09 00:21
It's still just hanging for me event after running `mix local.hex --force`.

**Comment by riverrun** [comment] 2020-01-15 02:46
Ok. One more suggestion: try running `mix deps.clean --unlock --unused`, and then run `mix deps.get`.

**Comment by lukashambsch** [comment] 2020-02-04 00:01
Sorry for the slow response. I tried running `mix deps.clean --unlock --unused`, then running `mix deps.get`. Unfortunately it's still hanging when I have `{:bcrypt_elixir, "~> 2.0"}` in my dependencies.

**Comment by riverrun** [comment] 2020-02-14 06:34
Someone using pbkdf2_elixir solved a similar issue by running ` HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get`.

**Comment by lukashambsch** [comment] 2020-02-16 17:38
Still no luck. Just hanging when I run that command too.

**Comment by riverrun** [comment] 2020-03-01 04:50
Sorry to hear you are still having these issues. I don't really know what to suggest to fix it at the moment, but if I hear of anything, I will let you know.

**Comment by lukashambsch** [comment] 2020-03-01 23:43
That's alright. I appreciate everything you've done to try & help. Thanks!

**Comment by Boubalou** [comment] 2020-04-06 17:19
I do have this issue when trying to use version 2.2 in my mix.exs.

My Dockerfile also hang and kill the process, using this setup:

```dockerfile
FROM hexpm/elixir:1.9.3-erlang-22.3-alpine-3.11.3 AS otp-builder`
```

**Comment by rodrigoporcionato** [comment] 2020-05-04 19:40
If you are a user windows, maybe the problem is relation to nmake

in your project elixir try it:

1- is necessary to have installed the vs studio. Check you location of vs is installed.

run 
`cmd /K "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
`
after this, execute mix deps.compile

**Comment by tatiesmars** [comment] 2021-06-28 13:45
I m having similar issue with this image 

```
FROM elixir:1.12.1-alpine 
```

What I dont understand is that it work on my laptop but not on remote server

**Comment by phcurado** [comment] 2021-07-06 18:27
> I m having similar issue with this image
> 
> ```
> FROM elixir:1.12.1-alpine 
> ```
> 
> What I dont understand is that it work on my laptop but not on remote server

I'm having the same issue, locally the image is compiling, on my CI is failing.

**Comment by dnsbty** [comment] 2021-07-17 02:30
I have the same issue with `elixir:1.12-alpine`. It looks like some sort of permission issue because when I have my Dockerfile just get dependencies but not download them and then run with `docker run -it my_app:latest "sh"` and then run `mix deps.compile` it gives me this error. But when I do the same thing with `docker run -it --privileged my_app:latest "sh"` then it compiles like normal. I'm not really sure where to go from there though.

**Comment by dnsbty** [comment] 2021-07-17 22:11
After playing around with this more today, it appears that the issue is with [a change in Alpine 3.14](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2). I found that via [this issue](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12519).

I was able to solve it by updating Docker Desktop. On a remote server, you would probably need to update docker and containerd depending on your exact setup.

The other option would be to switch to a different image that's based on Alpine 3.13.3 (the last version prior to the change). At the moment, I would probably recommend `hexpm/elixir:1.12.2-erlang-24.0.3-alpine-3.14.0`

**Comment by Ch4s3** [comment] 2021-11-12 04:06
Is there a good solution for this for newer `hexpm/elixir` versions which use a newer version of alpine?

**Comment by sicksid** [comment] 2022-03-12 07:59
for me what worked was to add this: 

`RUN apk --no-cache add git make gcc erlang-dev libc-dev`

to the docker image

**Comment by sicksid** [comment] 2022-03-14 18:31
specifically i think it was `libc-dev`

**Comment by mazz** [comment] 2023-04-21 00:01
> specifically i think it was `libc-dev`

You totally saved my butt. I thought I'd never be able to upgrade from my old configuration, but it was this tip that helped me. Thanks!

**Comment by riverrun** [comment] 2024-10-04 12:21
Closing this issue. If anyone feels like reopening, please let me know.

**Closed by riverrun** 2024-10-04 12:21 UTC
